#!/usr/bin/env node

/* eslint-disable fecs-no-require */
require('babel-register');
const startup = process.env.NODE_ENV === 'development'
    ? './lib/cli.js'
    : './dist/cli.js'
require(startup);
/* eslint-enable fecs-no-require */
